### ISSUE TITLE
Support uri-interfaces 2.x

### ISSUE THREAD

**Issue by veewee** [thephpleague/uri-manipulations#5]
## Issue summary

When using PHP 8, you cannot install both league/uri and league/uri-manipulations.
The reason behind this is because uri-manipulations does not support uri-interfaces v2, but `uri` requires this version starting from 6.0. Older versions of uri don't support PHP 8.
This results in an uninstallable set of dependencies:

```
composer require league/uri league/uri-manipulations                                                                                                                                                                               
```

```
Using version ^6.4 for league/uri
Using version ^1.5 for league/uri-manipulations
```

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/uri-interfaces 2.1.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires league/uri ^6.4 -> satisfiable by league/uri[6.4.0].
    - league/uri-manipulations 1.5.0 requires league/uri-interfaces ^1.0 -> satisfiable by league/uri-interfaces[1.0.0, 1.1.0, 1.1.1].
    - You can only install one version of a package, so only one of these can be installed: league/uri-interfaces[1.0.0, 1.1.0, 1.1.1, 2.1.0, 2.2.0].
    - league/uri 6.4.0 requires league/uri-interfaces ^2.1 -> satisfiable by league/uri-interfaces[2.1.0, 2.2.0].
    - Root composer.json requires league/uri-manipulations ^1.5 -> satisfiable by league/uri-manipulations[1.5.0].
```

However, It does install if you require an older version of league/uri:^5.3.

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| league uri manipulations version | ^1.5 |
| PHP | 8.0 |
| OS Platform |  all |

**Comment by nyamsprod** [comment]
@veewee thanks for using the uri packages. Unfortunately, league/uri-manipulations has been deprecated for more than 6 months and is super-seeded by either uri v6 or uri-components v2 as stated in the documentation website and both have been updated to support PHP8

**Comment by nyamsprod** [comment]
What I could do is added a warning on the github repo to point to the supported version. As far as I know all functionalities  from the package were transfered to the mentionned package above so upgrading should be straightforward

**Comment by veewee** [comment]
Sorry for bothering you with this. I was a bit confused and ended up requiring the correct package instead.
A notice could be handy - but it was mostly my bet!
